; NOTICE: This file does nothing if mechanics.broken_tools_drop_components is
; disabled.

[@options]
; The minimum drop rate percentage. A player with terrible luck will receive
; this percentage of the value of their broken gear back.
drop_rate_min=100
; The mid drop rate percentage; the peak of the triangular distribution. A
; player can expect to receive this percentage of the value of their broken gear
; back.
drop_rate_mid=100
; The max drop rate percentage. A player with incredible luck will receive this
; percentage of the value of their broken gear back.
drop_rate_max=100
; If all drop_rate options are set to the same thing, there will be no variance
; in the actual value received back upon break. Otherwise, the min/mid/max
; options provide the points for a triangular distribution. What this means is
; that values closer to mid are more likely, while values close to min and max
; are rare. If you'd prefer a uniform distribution, where all values are
; equally likely, set this to true. If this is set to true, drop_rate_mid is
; ignored.
drop_rate_uniform=true
; A random amount of the returned value is in "nuggets" and a random amount is
; in "ingots". If this is set to 1, it is guaranteed that if an ingot worth of
; value or more has been returned, then at least 1 ingot will be given instead
; of all nuggets. If this is set to 0, no guarantee is made. If this is set to
; *, then there will be no randomness in what is returned as ingots and what is
; returned as nuggets; as many ingots as possible will be returned, using
; nuggets only when necessary.
guaranteed_ingots=*
; If true, items that have Curse of Vanishing will not drop components when
; they break.
ignore_vanishing=true
; The amount of nuggets to "cheat" the player out of. Separate from drop rate.
cheat=0

; Syntax is space-delimited values. The first value is how many nuggets are in
; an ingot, the second value is the item ID or tag of the nugget, and the third
; value is the item ID or tag of the ingot. Nugget value can be arbitrarily low,
; and you can omit the third value if you only want nuggets to drop. You can
; read this as e.g. "9 gold_nugget[s are equivalent to 1] gold_ingot".
; Material names themselves are not namespaced. The namespace here in the
; section name is just for convenience when specifying tags and items.
[@materials.minecraft:]
wood=1 minecraft:dirt
; Example change: Always drop oak planks instead of random planks.
;wood=
leather=
chain=
stone=
gold=
iron=
diamond=
netherite=
stick=
flint=
string=
scute=

; Syntax is space-delimited values again. Number of values is arbitrary; prefix
; a material name (from up above) with a number to specify how much of that
; material it is worth. Suffix the value with a ! to make that material
; ignore the drop_rate and always drop its complete value. Suffix the value
; with * to have that component accept random enchantments from the original
; tool. (Note this isn't useful without mechanics.grindstone_disenchanting.)
; As of 1.3.2, you can also specify a material value for a fake "xp" material
; to drop experience.
[minecraft:]
bow=
crossbow=
shears=
flint_and_steel=
shield=
fishing_rod=1 wood!
turtle_helmet=

wooden_pickaxe=
stone_pickaxe=
golden_pickaxe=
iron_pickaxe=
diamond_pickaxe=
netherite_pickaxe=

wooden_axe=
stone_axe=
golden_axe=
iron_axe=
diamond_axe=
netherite_axe=

wooden_shovel=
stone_shovel=
golden_shovel=
iron_shovel=
diamond_shovel=
netherite_shovel=

wooden_hoe=
stone_hoe=
golden_hoe=
iron_hoe=
diamond_hoe=
netherite_hoe=

wooden_sword=
stone_sword=
golden_sword=
iron_sword=
diamond_sword=
netherite_sword=

leather_helmet=
chainmail_helmet=
golden_helmet=
iron_helmet=
diamond_helmet=
netherite_helmet=

leather_chestplate=
chainmail_chestplate=
golden_chestplate=
iron_chestplate=
diamond_chestplate=
netherite_chestplate=

leather_leggings=
chainmail_leggings=
golden_leggings=
iron_leggings=
diamond_leggings=
netherite_leggings=

leather_boots=
chainmail_boots=
golden_boots=
iron_boots=
diamond_boots=
netherite_boots=
