// priority: 0

ServerEvents.tags('block', event => {
    event.get('auditory:stone_ore_sounds')
    .add('kubejs:magnetite_ore')
    .add('kubejs:deepslate_magnetite_ore')
    .add('minecraft:gold_ore')
    .add('minecraft:deepslate_gold_ore')
    .add('caverns_and_chasms:silver_ore')
    .add('caverns_and_chasms:deepslate_silver_ore')
    .add('minecraft:deepslate_diamond_ore')
    .add('minecraft:deepslate_coal_ore')
    .add('minecraft:deepslate_iron_ore')
    .add('minecraft:deepslate_redstone_ore')
    .add('minecraft:deepslate_copper_ore')

    event.get('auditory:metal_sounds')
    .add('kubejs:iron_plating')
    .add('kubejs:iron_bars')
    .add('kubejs:copper_plating')
    .add('kubejs:cage')
    .add('kubejs:lantern')
    .add('kubejs:copper_block')
    .add('minecraft:lodestone')
    //event.get('auditory:gold_sounds')
    .add('kubejs:gold_bricks')
    .add('kubejs:silver_bricks')
    .add('caverns_and_chasms:silver_block')
    .add('minecraft:gold_block')
    .add('minecraft:diamond_block')

    event.get('auditory:gold_sounds')
    .remove('minecraft:gold_block')

    event.get('auditory:clay_brick_sounds')
    .add('quark:shingles')
    .add('quark:red_shingles')
    .add('quark:magenta_shingles')
    .add('quark:blue_shingles')
    .add('quark:cyan_shingles')
    .add('quark:green_shingles')
    .add('quark:yellow_shingles')
    .add('quark:white_shingles')
    .add('quark:black_shingles')
    .add('quark:orange_shingles')
    .add('quark:pink_shingles')
    .add('quark:light_gray_shingles')
    .add('quark:light_blue_shingles')
    .add('quark:brown_shingles')
    .add('quark:lime_shingles')
    .add('quark:gray_shingles')
    .add('quark:purple_shingles')
    //event.add('auditory:stone_brick_sounds')
    .add('kubejs:cobblestone_bricks')
    .add('kubejs:rubblestone_bricks')
    .add('kubejs:chert_bricks')
    .add('kubejs:tiles')
    .add('kubejs:brimstone_bricks')
    .add('kubejs:substrate_bricks')

    event.add('auditory:obsidian_sounds')
    .add('kubejs:brimstone')
    .add('respawn_block:bleeding_obsidian')

})
