palette.format=vanilla
screen.loading=373363
screen.loading.bar=373363
screen.loading.outline=373363
screen.loading.progress=373363
fog.nether=0A0000
fog.end=010101
text.boss=ff00ff
screen.loading.blend=off
lilypad=208031