
#Arrow configs
[arrows]
	#Damage multiplier for entities in water or entities that are aquatic.
	#Range: 1.0 ~ 1.7976931348623157E308
	electricDamageMultiplier = 2.0
	#Apply damage multiplier to non aquatic mobs.
	electricDamageNonAquaticMobs = true
	#List of all mobs and their sounds that can be gotten by the Voice Box Arrow.
	allowedMobVoices = ["minecraft:blaze;minecraft:entity.blaze.ambient", "minecraft:pillager;minecraft:entity.pillager.ambient", "minecraft:skeleton;minecraft:entity.skeleton.ambient", "minecraft:elder_guardian;minecraft:entity.elder_guardian.ambient", "minecraft:zoglin;minecraft:entity.zoglin.ambient", "minecraft:ravager;minecraft:entity.ravager.ambient", "minecraft:ghast;minecraft:entity.ghast.ambient", "minecraft:hoglin;minecraft:entity.hoglin.ambient", "minecraft:guardian;minecraft:entity.guardian.ambient", "minecraft:parrot;minecraft:entity.parrot.ambient", "minecraft:cow;minecraft:entity.cow.ambient", "minecraft:vindicator;minecraft:entity.vindicator.ambient", "minecraft:magma_cube;minecraft:entity.magma_cube.squish", "minecraft:piglin_brute;minecraft:entity.piglin_brute.ambient", "minecraft:spider;minecraft:entity.spider.ambient", "minecraft:creeper;minecraft:entity.creeper.primed", "minecraft:warden;minecraft:entity.warden.ambient", "minecraft:wither;minecraft:entity.wither.ambient", "minecraft:evoker;minecraft:entity.evoker.ambient", "minecraft:slime;minecraft:entity.slime.squish", "minecraft:polar_bear;minecraft:entity.polar_bear.ambient", "minecraft:bat;minecraft:entity.bat.ambient", "minecraft:illusioner;minecraft:entity.illusioner.ambient", "minecraft:phantom;minecraft:entity.phantom.ambient", "minecraft:witch;minecraft:entity.witch.ambient", "minecraft:wither_skeleton;minecraft:entity.wither_skeleton.ambient", "minecraft:llama;minecraft:entity.llama.ambient", "minecraft:pig;minecraft:entity.pig.ambient", "minecraft:husk;minecraft:entity.husk.ambient", "minecraft:sheep;minecraft:entity.sheep.ambient", "minecraft:ender_dragon;minecraft:entity.ender_dragon.ambient", "minecraft:shulker;minecraft:entity.shulker.ambient", "minecraft:cave_spider;minecraft:entity.spider.ambient", "minecraft:piglin;minecraft:entity.piglin.ambient", "minecraft:ocelot;minecraft:entity.ocelot.ambient", "minecraft:silverfish;minecraft:entity.silverfish.ambient", "minecraft:stray;minecraft:entity.stray.ambient", "minecraft:endermite;minecraft:entity.endermite.ambient", "minecraft:chicken;minecraft:entity.chicken.ambient", "minecraft:vex;minecraft:entity.vex.ambient", "minecraft:zombie;minecraft:entity.zombie.ambient", "minecraft:drowned;minecraft:entity.drowned.ambient", "minecraft:wolf;minecraft:entity.wolf.ambient", "minecraft:zombie_villager;minecraft:entity.zombie_villager.ambient"]

#Arrow Trades
[trades]
	#0 = not sold.
	#Range: 0 ~ 64
	"pulse_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"guilded_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"soul_torch_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"voice_box_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"frost_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"egg_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"glass_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"better_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"torch_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"random_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"lit_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"parcel_arrowTrade Cost" = 0
	#0 = not sold.
	#Range: 0 ~ 64
	"electric_arrowTrade Cost" = 0

